"use client";

import store from "../store/index";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import ToastifyProviver from "../providers/ToastifyProviver";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ToastifyProviver>{children}</ToastifyProviver>
        </Provider>
      </body>
    </html>
  );
}
